-- AlterTable
ALTER TABLE `tbcliente` MODIFY `telefoneCliente` VARCHAR(20) NOT NULL,
    MODIFY `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updated_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
